### ISSUE TITLE
distributed actors

### ISSUE THREAD

**Issue by massivefermion** [akka-js/akka.js_bindings#3]
Hi
as far as i know, akka is able to spawn remote actors. Is it possible in akka.js too? How?
Thakns

**Comment by andreaTP** [comment]
Hi @MassiveFermion ,
remote actors are not available "out-of-the-box" unfortunately. Still you are totally able to spawn actors in different VMs and make them communicate as demonstrated e.g. [here](https://github.com/akka-js/akka.js-dom/blob/master/demo/5-pingpong/main.js#L5).

If anything useful is missing from the JS API just file an issue!
