### ISSUE TITLE
[Question] i am guessing there are no plans for this to be rewritten in javascript friendly way? Also either rewrite it in typescript / or add support for it?

### ISSUE THREAD

**Issue by vladimir-ivanov** [akka-js/akka.js_bindings#4]

**Comment by andreaTP** [comment]
Not sure about this question, Akka is written in Scala and writing a Scala.js facade for it is the way to expose it to the JS world. I'm aware of libraries/tools that are doing TS to Scala.js but not vice-versa, at best of my knowledge.

A TS friendly facade would be really cool though

**Comment by vladimir-ivanov** [comment]
:-) first part of the question was whether it is worth re writing in javascript, rather than generating js code out of scala, so it becomes maintainable on its own right. But that would be a lot of work.

second part is yes, to bring the types into typescript and expose interfaces types etc

**Comment by andreaTP** [comment]
Here we are cross-compiling 150+K LOC from the Akka codebase... For sure it's not going to be my business rewriting all of it (although they did it in .NET world).

Second part PRs are very welcome! :-)

**Comment by vladimir-ivanov** [comment]
https://github.com/scala-ts/scala-ts or https://github.com/scala-tsi/scala-tsi - would any of these work to generrate the Akka to ts definitions?

**Comment by vladimir-ivanov** [comment]
how is the spawn working/ implemented in the browser please? Can you envisage any benefits of it in the browser?
